#!/usr/bin/env bash
# Create a 404 error page
sudo apt-get update
sudo apt-get install -y nginx
sudo service nginx start
sudo sed -i "s/#error_page 404/error_page 404/" /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
sudo service nginx restart
